//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWebApp.ProductRecommendation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://onlinestore.example.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://onlinestore.example.com/", ConfigurationName="ProductRecommendation.ProductRecommendationSoap")]
    public interface ProductRecommendationSoap {
        
        // CODEGEN: Generating message contract since element name productCategory from namespace http://onlinestore.example.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://onlinestore.example.com/GetRecommendations", ReplyAction="*")]
        ShopWebApp.ProductRecommendation.GetRecommendationsResponse GetRecommendations(ShopWebApp.ProductRecommendation.GetRecommendationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onlinestore.example.com/GetRecommendations", ReplyAction="*")]
        System.Threading.Tasks.Task<ShopWebApp.ProductRecommendation.GetRecommendationsResponse> GetRecommendationsAsync(ShopWebApp.ProductRecommendation.GetRecommendationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecommendationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecommendations", Namespace="http://onlinestore.example.com/", Order=0)]
        public ShopWebApp.ProductRecommendation.GetRecommendationsRequestBody Body;
        
        public GetRecommendationsRequest() {
        }
        
        public GetRecommendationsRequest(ShopWebApp.ProductRecommendation.GetRecommendationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://onlinestore.example.com/")]
    public partial class GetRecommendationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productCategory;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string priceRange;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userID;
        
        public GetRecommendationsRequestBody() {
        }
        
        public GetRecommendationsRequestBody(string productCategory, string priceRange, string userID) {
            this.productCategory = productCategory;
            this.priceRange = priceRange;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecommendationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecommendationsResponse", Namespace="http://onlinestore.example.com/", Order=0)]
        public ShopWebApp.ProductRecommendation.GetRecommendationsResponseBody Body;
        
        public GetRecommendationsResponse() {
        }
        
        public GetRecommendationsResponse(ShopWebApp.ProductRecommendation.GetRecommendationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://onlinestore.example.com/")]
    public partial class GetRecommendationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ShopWebApp.ProductRecommendation.ArrayOfString GetRecommendationsResult;
        
        public GetRecommendationsResponseBody() {
        }
        
        public GetRecommendationsResponseBody(ShopWebApp.ProductRecommendation.ArrayOfString GetRecommendationsResult) {
            this.GetRecommendationsResult = GetRecommendationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductRecommendationSoapChannel : ShopWebApp.ProductRecommendation.ProductRecommendationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductRecommendationSoapClient : System.ServiceModel.ClientBase<ShopWebApp.ProductRecommendation.ProductRecommendationSoap>, ShopWebApp.ProductRecommendation.ProductRecommendationSoap {
        
        public ProductRecommendationSoapClient() {
        }
        
        public ProductRecommendationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductRecommendationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductRecommendationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductRecommendationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShopWebApp.ProductRecommendation.GetRecommendationsResponse ShopWebApp.ProductRecommendation.ProductRecommendationSoap.GetRecommendations(ShopWebApp.ProductRecommendation.GetRecommendationsRequest request) {
            return base.Channel.GetRecommendations(request);
        }
        
        public ShopWebApp.ProductRecommendation.ArrayOfString GetRecommendations(string productCategory, string priceRange, string userID) {
            ShopWebApp.ProductRecommendation.GetRecommendationsRequest inValue = new ShopWebApp.ProductRecommendation.GetRecommendationsRequest();
            inValue.Body = new ShopWebApp.ProductRecommendation.GetRecommendationsRequestBody();
            inValue.Body.productCategory = productCategory;
            inValue.Body.priceRange = priceRange;
            inValue.Body.userID = userID;
            ShopWebApp.ProductRecommendation.GetRecommendationsResponse retVal = ((ShopWebApp.ProductRecommendation.ProductRecommendationSoap)(this)).GetRecommendations(inValue);
            return retVal.Body.GetRecommendationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShopWebApp.ProductRecommendation.GetRecommendationsResponse> ShopWebApp.ProductRecommendation.ProductRecommendationSoap.GetRecommendationsAsync(ShopWebApp.ProductRecommendation.GetRecommendationsRequest request) {
            return base.Channel.GetRecommendationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShopWebApp.ProductRecommendation.GetRecommendationsResponse> GetRecommendationsAsync(string productCategory, string priceRange, string userID) {
            ShopWebApp.ProductRecommendation.GetRecommendationsRequest inValue = new ShopWebApp.ProductRecommendation.GetRecommendationsRequest();
            inValue.Body = new ShopWebApp.ProductRecommendation.GetRecommendationsRequestBody();
            inValue.Body.productCategory = productCategory;
            inValue.Body.priceRange = priceRange;
            inValue.Body.userID = userID;
            return ((ShopWebApp.ProductRecommendation.ProductRecommendationSoap)(this)).GetRecommendationsAsync(inValue);
        }
    }
}
