//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWebApp.CheckoutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CheckoutService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkout", ReplyAction="http://tempuri.org/IService1/checkoutResponse")]
        System.Collections.Generic.Dictionary<string, string> checkout(System.Collections.Generic.Dictionary<string, string>[] shoppingCartItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkout", ReplyAction="http://tempuri.org/IService1/checkoutResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> checkoutAsync(System.Collections.Generic.Dictionary<string, string>[] shoppingCartItems);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ShopWebApp.CheckoutService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ShopWebApp.CheckoutService.IService1>, ShopWebApp.CheckoutService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, string> checkout(System.Collections.Generic.Dictionary<string, string>[] shoppingCartItems) {
            return base.Channel.checkout(shoppingCartItems);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> checkoutAsync(System.Collections.Generic.Dictionary<string, string>[] shoppingCartItems) {
            return base.Channel.checkoutAsync(shoppingCartItems);
        }
    }
}
